resources:
- name: repo
  type: git
  source:
    uri: https://github.com/StefanKosztur/Test.git
    
jobs:
- name: hello-world-job
  plan:
  - get: repo
    trigger: true
  - task: hello-world-task
    file: repo/Concourse/task-hello-world/task_hello_world.yml 
run:
  path: echo
  args: [hello world]